services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: python-api

    ports:
      - "8000:8000"

    env_file:
      - ./ai_service_demo/.env

    volumes:
      # Mount backend source code for live reload
      - ./app:/app/app
      - ./ai_service_demo:/app/ai_service_demo
      - ./common:/app/common
      - ./workers:/app/workers

      # Keep container's virtual environment
      - /app/.venv

    environment:
      PYTHONUNBUFFERED: "1"
      WATCHFILES_FORCE_POLLING: "true"

    command:
      - uv
      - run
      - uvicorn
      - app.app:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /app/app
      - --reload-dir
      - /app/ai_service_demo
      - --reload-dir
      - /app/common
      - --reload-dir
      - /app/workers