services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: python-api

    ports:
      - "8000:8000"

    env_file:
      - ./ai_service_demo/.env

    volumes:
      # Mount source code
      - ./app:/app/app

      # Keep container's virtual environment
      - /app/.venv

    environment:
      PYTHONUNBUFFERED: "1"

    command:
      - uv
      - run
      - uvicorn
      - app.app:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /app/app