import {
  Shield,
  SearchCheck,
} from "lucide-react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";

// import type { CBOM } from "@/types/cbom";

interface ExecutiveSummaryProps {
  selectedReport?: {
    id?: string;
    executive_summary?: string;
    report_json?: any;
  } | null;

  seedCBOM: any;
}

export function ExecutiveSummary({
  selectedReport,
  seedCBOM,
}: ExecutiveSummaryProps) {
  const cbom =
    selectedReport?.report_json ?? seedCBOM;

  return (
    <div className="space-y-6 pb-8">

      {/* HEADER */}
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">

        <div className="flex items-center gap-3">

          <div className="flex size-10 items-center justify-center rounded-lg bg-primary/10">
            <Shield className="size-5 text-primary" />
          </div>

          <div>
            <h2 className="text-xl font-semibold tracking-tight">
              Executive Security Summary
            </h2>

            <p className="text-sm text-muted-foreground">
              Cryptographic posture and post-quantum migration assessment
            </p>
          </div>

        </div>

        <Badge
          variant="destructive"
          className="w-fit px-3 py-1"
        >
          HIGH RISK
        </Badge>

      </div>


      {/* KPI CARDS */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">

        <Card>
          <CardHeader className="pb-2">
            <CardDescription>
              Overall Risk
            </CardDescription>

            <CardTitle className="text-3xl">
              78
              <span className="text-sm font-normal text-muted-foreground">
                /100
              </span>
            </CardTitle>
          </CardHeader>

          <CardContent>
            <Progress value={78} />

            <p className="mt-2 text-xs text-muted-foreground">
              High cryptographic exposure
            </p>
          </CardContent>
        </Card>


        <Card>
          <CardHeader className="pb-2">
            <CardDescription>
              Quantum Readiness
            </CardDescription>

            <CardTitle className="text-3xl">
              42%
            </CardTitle>
          </CardHeader>

          <CardContent>
            <Progress value={42} />

            <p className="mt-2 text-xs text-muted-foreground">
              Migration partially started
            </p>
          </CardContent>
        </Card>


        <Card>
          <CardHeader className="pb-2">
            <CardDescription>
              Quantum Vulnerable
            </CardDescription>

            <CardTitle className="text-3xl text-destructive">
              8
            </CardTitle>
          </CardHeader>

          <CardContent>
            <p className="text-xs text-muted-foreground">
              Assets affected by quantum threats
            </p>
          </CardContent>
        </Card>


        <Card>
          <CardHeader className="pb-2">
            <CardDescription>
              PQC Adoption
            </CardDescription>

            <CardTitle className="text-3xl">
              27%
            </CardTitle>
          </CardHeader>

          <CardContent>
            <Progress value={27} />

            <p className="mt-2 text-xs text-muted-foreground">
              Post-quantum algorithms detected
            </p>
          </CardContent>
        </Card>

      </div>


      {/* AI ASSESSMENT */}
      <Card className="border-primary/20">

        <CardHeader>

          <div className="flex items-start justify-between">

            <div className="flex gap-3">

              <div className="flex size-10 items-center justify-center rounded-lg bg-primary/10">
                <SearchCheck className="size-5 text-primary" />
              </div>

              <div>
                <CardTitle className="text-base">
                  AI Security Assessment
                </CardTitle>

                <CardDescription>
                  Generated by the QShieldX Reporting Agent
                </CardDescription>
              </div>

            </div>

            <Badge variant="outline">
              AI Analysis
            </Badge>

          </div>

        </CardHeader>

        <CardContent>

          {selectedReport?.executive_summary ? (

            <div className="rounded-lg border bg-muted/30 p-4">
              <p className="whitespace-pre-wrap text-sm leading-7 text-muted-foreground">
                {selectedReport.executive_summary}
              </p>
            </div>

          ) : (

            <div className="space-y-4">

              <p className="text-sm leading-7 text-muted-foreground">
                QShieldX has completed a cryptographic discovery
                assessment across the target infrastructure.
              </p>

              <p className="text-sm leading-7 text-muted-foreground">
                The analysis identified classical public-key
                cryptography, legacy protocols and post-quantum
                cryptographic assets.
              </p>

            </div>

          )}

        </CardContent>

      </Card>


      {/* FINDINGS + ROADMAP */}
      <div className="grid gap-6 lg:grid-cols-2">

        {/* FINDINGS */}
        <Card>

          <CardHeader>

            <div className="flex items-center justify-between">

              <div>
                <CardTitle className="text-base">
                  Key Findings
                </CardTitle>

                <CardDescription>
                  Highest-impact cryptographic observations
                </CardDescription>
              </div>

              <Badge variant="destructive">
                3 Findings
              </Badge>

            </div>

          </CardHeader>

          <CardContent className="space-y-4">

            <div className="flex gap-3">

              <div className="mt-1 size-2.5 shrink-0 rounded-full bg-destructive" />

              <div className="flex-1">

                <div className="flex items-center justify-between">
                  <p className="text-sm font-medium">
                    RSA-2048
                  </p>

                  <Badge variant="destructive">
                    Critical
                  </Badge>
                </div>

                <p className="mt-1 text-xs leading-5 text-muted-foreground">
                  Public-key cryptography requiring
                  post-quantum migration planning.
                </p>

              </div>

            </div>

            <Separator />

            <div className="flex gap-3">

              <div className="mt-1 size-2.5 shrink-0 rounded-full bg-destructive" />

              <div className="flex-1">

                <div className="flex items-center justify-between">
                  <p className="text-sm font-medium">
                    ECDSA P-256
                  </p>

                  <Badge variant="destructive">
                    High
                  </Badge>
                </div>

                <p className="mt-1 text-xs leading-5 text-muted-foreground">
                  Elliptic-curve signature algorithm
                  requiring migration planning.
                </p>

              </div>

            </div>

            <Separator />

            <div className="flex gap-3">

              <div className="mt-1 size-2.5 shrink-0 rounded-full bg-yellow-500" />

              <div className="flex-1">

                <div className="flex items-center justify-between">
                  <p className="text-sm font-medium">
                    TLS 1.2
                  </p>

                  <Badge variant="outline">
                    Medium
                  </Badge>
                </div>

                <p className="mt-1 text-xs leading-5 text-muted-foreground">
                  Legacy transport configuration
                  detected.
                </p>

              </div>

            </div>

          </CardContent>

        </Card>


        {/* ROADMAP */}
        <Card>

          <CardHeader>
            <CardTitle className="text-base">
              Migration Roadmap
            </CardTitle>

            <CardDescription>
              Cryptographic modernization phases
            </CardDescription>
          </CardHeader>

          <CardContent>

            <div className="space-y-6">

              <div className="flex gap-4">

                <div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-destructive/10 text-xs font-semibold text-destructive">
                  1
                </div>

                <div>
                  <p className="text-sm font-medium">
                    Immediate Remediation
                  </p>

                  <p className="mt-1 text-xs leading-5 text-muted-foreground">
                    Identify vulnerable RSA/ECC assets
                    and legacy protocols.
                  </p>
                </div>

              </div>


              <div className="flex gap-4">

                <div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-yellow-500/10 text-xs font-semibold text-yellow-600">
                  2
                </div>

                <div>
                  <p className="text-sm font-medium">
                    Hybrid Migration
                  </p>

                  <p className="mt-1 text-xs leading-5 text-muted-foreground">
                    Introduce classical and post-quantum
                    hybrid mechanisms.
                  </p>
                </div>

              </div>


              <div className="flex gap-4">

                <div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">
                  3
                </div>

                <div>
                  <p className="text-sm font-medium">
                    PQC Adoption
                  </p>

                  <p className="mt-1 text-xs leading-5 text-muted-foreground">
                    Expand ML-KEM, ML-DSA and other
                    approved post-quantum mechanisms.
                  </p>
                </div>

              </div>

            </div>

          </CardContent>

        </Card>

      </div>


      {/* CRYPTOGRAPHIC POSTURE */}
      <Card>

        <CardHeader>

          <CardTitle className="text-base">
            Cryptographic Posture
          </CardTitle>

          <CardDescription>
            Distribution of discovered cryptographic assets
          </CardDescription>

        </CardHeader>

        <CardContent>

          <div className="grid gap-6 md:grid-cols-3">

            <PostureItem
              title="Quantum Vulnerable"
              value="8"
              progress={36}
              description="Assets affected by quantum threats."
            />

            <PostureItem
              title="Quantum Resistant"
              value="6"
              progress={27}
              description="Assets using resistant mechanisms."
            />

            <PostureItem
              title="Legacy"
              value="4"
              progress={18}
              description="Deprecated configurations."
            />

          </div>

        </CardContent>

      </Card>


      {/* RECOMMENDED ACTIONS */}
      <Card>

        <CardHeader>

          <CardTitle className="text-base">
            Recommended Actions
          </CardTitle>

          <CardDescription>
            Prioritized remediation actions
          </CardDescription>

        </CardHeader>

        <CardContent>

          <div className="space-y-3">

            <ActionItem
              number="01"
              title="Upgrade internal certificate infrastructure"
              description="Evaluate hybrid ML-KEM/RSA certificate deployment."
              priority="Critical"
              destructive
            />

            <ActionItem
              number="02"
              title="Rotate exposed cryptographic secrets"
              description="Move hardcoded secrets into a managed key or secrets system."
              priority="High"
            />

            <ActionItem
              number="03"
              title="Modernize TLS configuration"
              description="Remove deprecated TLS versions and review cipher suites."
              priority="Medium"
            />

          </div>

        </CardContent>

      </Card>


      {/* SCAN METADATA */}
      <Card className="bg-muted/20">

        <CardContent className="pt-6">

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">

            <Metadata
              label="Scan ID"
              value={selectedReport?.id ?? "scan-2026-09-15-001"}
            />

            <Metadata
              label="Scan Status"
              value="Completed"
            />

            <Metadata
              label="Scanner"
              value="QShieldX CBOM Engine"
            />

            <Metadata
              label="Analysis Duration"
              value="48.2 seconds"
            />

          </div>

        </CardContent>

      </Card>

    </div>
  );
}

interface PostureItemProps {
  title: string;
  value: string;
  progress: number;
  description: string;
}

function PostureItem({
  title,
  value,
  progress,
  description,
}: PostureItemProps) {
  return (
    <div className="space-y-3">

      <div className="flex items-center justify-between">
        <span className="text-sm">
          {title}
        </span>

        <span className="text-sm font-semibold">
          {value}
        </span>
      </div>

      <Progress value={progress} />

      <p className="text-xs text-muted-foreground">
        {description}
      </p>

    </div>
  );
}

interface ActionItemProps {
  number: string;
  title: string;
  description: string;
  priority: string;
  destructive?: boolean;
}

function ActionItem({
  number,
  title,
  description,
  priority,
  destructive,
}: ActionItemProps) {
  return (
    <div className="flex items-center gap-4 rounded-lg border p-4">

      <div
        className={`flex size-9 shrink-0 items-center justify-center rounded-lg ${
          destructive
            ? "bg-destructive/10"
            : "bg-primary/10"
        }`}
      >
        <span
          className={`text-sm font-bold ${
            destructive
              ? "text-destructive"
              : "text-primary"
          }`}
        >
          {number}
        </span>
      </div>

      <div className="flex-1">

        <p className="text-sm font-medium">
          {title}
        </p>

        <p className="text-xs text-muted-foreground">
          {description}
        </p>

      </div>

      <Badge
        variant={
          destructive
            ? "destructive"
            : "outline"
        }
      >
        {priority}
      </Badge>

    </div>
  );
}

interface MetadataProps {
  label: string;
  value: string;
}

function Metadata({
  label,
  value,
}: MetadataProps) {
  return (
    <div>

      <p className="text-xs text-muted-foreground">
        {label}
      </p>

      <p className="mt-1 text-xs font-medium">
        {value}
      </p>

    </div>
  );
}